MyFinancePlanner/MyFinancePlanner.Web/Controllers/GroupController.cs
using System;
using System.Web.Mvc;
using MyFinancePlanner.Core.Factory;
using MyFinancePlanner.Core.ObjectValues;
using MyFinancePlanner.Web.Process;

namespace MyFinancePlanner.Web.Controllers
{
    public class GroupController : Controller
    {
        //
        // GET: /Group/

        public ActionResult Index()
        {
            var usecase = new GetLedgerGroups();
            return View(usecase.Do());
        }

        //
        // GET: /Group/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Group/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Group/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Group/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Group/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Group/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Group/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GetGetLedgerContract
        public ActionResult ContractDetail(Guid id)
        {
            var usecase = Factory.CreateObject<GetGetLedgerContract>();
            usecase.Do(new Id(id));

            return View(usecase);
        }
    }
}

MyFinancePlanner/MyFinancePlanner.Web/Controllers/PaymentController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using MyFinancePlanner.Core.Factory;
using MyFinancePlanner.Core.ObjectValues;
using MyFinancePlanner.Web.Models;
using MyFinancePlanner.Web.Process;

namespace MyFinancePlanner.Web.Controllers
{
    public class PaymentController : Controller
    {
        //
        // GET: /Payment/

        public ActionResult Index()
        {
            var usecase = Factory.CreateObject<GetTransactions>();
            usecase.Do();
            return View(usecase);
        }

        //
        // GET: /Payment/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Payment/Create

        public ActionResult Create()
        {
            var usecase = Factory.CreateObject<PaymentsDetail>();
            usecase.Do();

            return View(usecase);
        }

        //
        // POST: /Payment/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var payment = Factory.CreateObject<Payments>();
                payment.ContractName = collection["ContractName"];
                payment.FinancialYearId = new Id(collection["FinancialYearId"]);
                payment.GroupId = new Id(collection["GroupId"]);
                payment.ContractId = new Id();
                payment.Cost = decimal.Parse(collection["cost"]);
                payment.ProcessingDate = DateTime.Parse(collection["ProcessingDate"], new CultureInfo("nl-NL"));
                payment.InterestDate = !string.IsNullOrEmpty(collection["InterestDate"]) ? DateTime.Parse(collection["InterestDate"], new CultureInfo("nl-NL")) as DateTime? : null as DateTime?;
                payment.ContractGuid = !string.IsNullOrEmpty(collection["ContractGuid"]) ? new Id(new Guid(collection["ContractGuid"])) : new Id(Guid.Empty);

                Factory.CreateObject<AddPayment>().Do(payment);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Payment/Edit/5

        public ActionResult Edit(Guid id)
        {
            var usecase = Factory.CreateObject<PaymentsDetail>();
            usecase.Do(new Id(id));

            return View(usecase);
        }

        //
        // POST: /Payment/Edit/5
        //public ActionResult Edit(int id, FormCollection collection)
        [HttpPost]
        public ActionResult Edit(Guid id, FormCollection collection)
         {
            try
            {
                var action = collection["button"];
                if (action == "delete")
                {
                    Factory.CreateObject<RemovePayment>().Do(new Id(id));    
                }
                else
                {
                    var payment = Factory.CreateObject<Payments>();
                    payment.FinancialYearId = new Id(collection["FinancialYearId"]);
                    payment.GroupId = new Id(collection["GroupId"]);
                    payment.ContractId = new Id(id);
                    payment.Cost = decimal.Parse(collection["cost"]);
                    payment.ProcessingDate = DateTime.Parse(collection["ProcessingDate"], new CultureInfo("nl-NL"));
                    payment.InterestDate = !string.IsNullOrEmpty(collection["InterestDate"]) ? DateTime.Parse(collection["InterestDate"], new CultureInfo("nl-NL")) as DateTime? : null as DateTime?;

                    Factory.CreateObject<ConfirmPayment>().Do(payment);    
                }
                
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Payment/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Payment/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyFinancePlanner/MyFinancePlanner.Web/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>My Finance Planner - @ViewBag.Title</title>
    @Styles.Render("~/libs/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="/libs/css/bootstrap.min.css" >
     <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>

<div class="container-fluid">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">My Finance Planner</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li>@Html.ActionLink("Transactions", "Index", "Payment")</li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maintenance <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Createbook year</a></li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">User</a></li>
                    </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Create payment", "Create", "Payment")</li>
              </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    @RenderBody()
</div>


@Scripts.Render("~/bundles/jquery")
@RenderSection("scripts", required: false)

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script type="text/javascript" src="/libs/js/moment.min.js"></script>
<script type="text/javascript" src="/libs/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="/libs/js/local.js"></script>
</body>
</html>